schtasks /create /xml "windows-tasks\BC-1.xml" /TN "MU Robot\BC-1"
schtasks /create /xml "windows-tasks\DS-1.xml"  /TN "MU Robot\DS-1"
schtasks /create /xml "windows-tasks\BC-2.xml"  /TN "MU Robot\BC-2"
schtasks /create /xml "windows-tasks\DS-2.xml"  /TN "MU Robot\DS-2"
schtasks /create /xml "windows-tasks\BC-3.xml"  /TN "MU Robot\BC-3"
schtasks /create /xml "windows-tasks\DS-3.xml"  /TN "MU Robot\DS-3"
schtasks /create /xml "windows-tasks\BC-4.xml"  /TN "MU Robot\BC-4"
schtasks /create /xml "windows-tasks\DS-4.xml"  /TN "MU Robot\DS-4"
schtasks /create /xml "windows-tasks\Colosseum.xml"  /TN "MU Robot\Colosseum"
schtasks /create /xml "windows-tasks\EXP(x3)+ZEN.xml"  /TN "MU Robot\EXP(x3)+ZEN"
schtasks /create /xml "windows-tasks\Collect.xml"  /TN "MU Robot\Collect"
schtasks /create /xml "windows-tasks\Kalima.xml"  /TN "MU Robot\Kalima"
schtasks /create /xml "windows-tasks\DailyTargetQuests.xml"  /TN "MU Robot\DailyTargetQuests"
schtasks /create /xml "windows-tasks\Corps.xml"  /TN "MU Robot\Corps"
pause