schtasks /create /xml "windows-tasks\night\BC-1.xml" /TN "MU Robot\BC-1"
schtasks /create /xml "windows-tasks\night\DS-1.xml" /TN "MU Robot\DS-1"
schtasks /create /xml "windows-tasks\night\BC-2.xml" /TN "MU Robot\BC-2"
schtasks /create /xml "windows-tasks\night\DS-2.xml" /TN "MU Robot\DS-2"
schtasks /create /xml "windows-tasks\night\BC-3.xml" /TN "MU Robot\BC-3"
schtasks /create /xml "windows-tasks\night\DS-3.xml" /TN "MU Robot\DS-3"
schtasks /create /xml "windows-tasks\night\BC-4.xml" /TN "MU Robot\BC-4"
schtasks /create /xml "windows-tasks\night\DS-4.xml" /TN "MU Robot\DS-4"
schtasks /create /xml "windows-tasks\night\Colosseum.xml" /TN "MU Robot\Colosseum"
schtasks /create /xml "windows-tasks\night\EXP(x3)+ZEN.xml" /TN "MU Robot\EXP(x3)+ZEN"
schtasks /create /xml "windows-tasks\night\Collect.xml" /TN "MU Robot\Collect"
pause