schtasks /delete /tn "MU Robot\BC-1" /f
schtasks /delete /tn "MU Robot\DS-1" /f
schtasks /delete /tn "MU Robot\BC-2" /f
schtasks /delete /tn "MU Robot\DS-2" /f
schtasks /delete /tn "MU Robot\BC-3" /f
schtasks /delete /tn "MU Robot\DS-3" /f
schtasks /delete /tn "MU Robot\BC-4" /f
schtasks /delete /tn "MU Robot\DS-4" /f
schtasks /delete /tn "MU Robot\BC-5" /f
schtasks /delete /tn "MU Robot\DS-5" /f
schtasks /delete /tn "MU Robot\Other" /f
